
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcnygpdpsczbcjsaqetk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbnlncGRwc2N6YmNqc2FxZXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDEzMTMsImV4cCI6MjA2MzIxNzMxM30.EITt_EuqLxvjvTfD3G77BD5DXf07o2RCv0zw60hu9TA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
